kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - containerPath: /etc/kubernetes/encryption/encryption-conf.yaml
    hostPath: /Users/kaijun/Go/src/kms/pkg/scripts/kms-encryption-conf.yaml
    readOnly: true
    propagation: None
  - containerPath: /etc/kubernetes/manifests/plugin.yaml
    hostPath: /Users/kaijun/Go/src/kms/pkg/scripts/plugin.yaml
    readOnly: true
    propagation: None
  kubeadmConfigPatches:
    - |
      kind: ClusterConfiguration
      apiServer:
        extraArgs:
          feature-gates: "KMSv2=true"
          encryption-provider-config: "/etc/kubernetes/enc/encryption-conf.yaml"
          v: "5"
        extraVolumes:
        - name: enc-vol
          hostPath: "/etc/kubernetes/encryption/encryption-conf.yaml"
          mountPath: "/etc/kubernetes/enc/encryption-conf.yaml"
          readOnly: true
          type: File
        - name: sock-path
          hostPath: "/tmp"
          mountPath: "/tmp"
          type: DirectoryOrCreate
      scheduler:
        extraArgs:
          v: "5"
      controllerManager:
        extraArgs:
          v: "5"