apiVersion: v1
kind: Pod
metadata:
  name: mock-kmsv2-provider
  namespace: kube-system
  labels:
    tier: control-plane
    component: mock-kmsv2-provider
spec:
  hostNetwork: true
  containers:
    - name: mock-kmsv2-provider
      image: kaijun123/kubernetes-kms:v4
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: sock-path
          mountPath: /tmp
  volumes:
    - name: sock-path
      hostPath:
        path: /tmp
        type: DirectoryOrCreate